# apiVersion: v1
# kind: Service
# metadata:
#   name: texttospeech-service
# spec:
#   type: NodePort
#   ports:
#     - name: http
#       protocol: TCP
#       port: 5003
#       targetPort: 5003
#       nodePort: 30002
#   selector:
#     app: texttospeech-deplyoment

apiVersion: v1
kind: Service
metadata:
  name: texttospeech-service
spec:
  type: LoadBalancer
  selector:
    app:  texttospeech-deplyoment
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 5003